services:
  mysql:
    container_name: mysql
    image: mysql:9
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./compose/mysql/init:/docker-entrypoint-initdb.d
      - ./compose/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: local_db
      MYSQL_USER: local_user
      MYSQL_PASSWORD: local_pass
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -u$${MYSQL_USER} -p$${MYSQL_PASSWORD}"]
      timeout: 5s
      interval: 5s
      retries: 5
      start_period: 5s
  postgres:
    container_name: postgres
    image: postgres:17beta2
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./compose/postgres/init:/docker-entrypoint-initdb.d
      - ./compose/postgres/postgresql.conf:/etc/postgresql/postgresql.conf
    environment:
      POSTGRES_DB: local_db
      POSTGRES_USER: local_user
      POSTGRES_PASSWORD: local_pass
      POSTGRES_INIT_DB_ARGS: --encoding=UTF-8
    # healthcheck:
    #   test: ["CMD-SHELL", "pg_isready"]
    #   interval: 5s
    #   timeout: 5s
    #   retries: 5
    #   start_period: 5s
