services:
  postgres:
    container_name: postgres
    image: postgres:17beta3
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./compose/postgres/init:/docker-entrypoint-initdb.d
      - ./compose/postgres/postgresql.conf:/etc/postgresql/postgresql.conf
    environment:
      POSTGRES_DB: local_db
      POSTGRES_USER: local_user
      POSTGRES_PASSWORD: local_pass
      POSTGRES_INIT_DB_ARGS: --encoding=UTF-8
    # healthcheck:
    #   test: ["CMD-SHELL", "pg_isready"]
    #   interval: 5s
    #   timeout: 5s
    #   retries: 5
    #   start_period: 5s
