version: "3"

tasks:
  init:
    cmds:
      - cp apps/api/.env.example apps/api/.env.local
      - cp apps/web/.env.example apps/web/.env.local

  clean:
    cmds:
      - find . -name '.turbo' -type d -prune -exec rm -rf '{}' +
      - find . -name 'build' -type d -prune -exec rm -rf '{}' +
      - find . -name 'generated' -type d -prune -exec rm -rf '{}' +
      - find . -name 'node_modules' -type d -prune -exec rm -rf '{}' +
      - find . -name 'pnpm-lock.yaml' -type f -prune -exec rm -rf '{}' +
      - find . -name 'tsconfig.tsbuildinfo' -type f -prune -exec rm -rf '{}' +

  up:
    cmds:
      - docker compose up -d --wait --wait-timeout=60
  down:
    cmds:
      - docker compose down
  db:
    cmds:
      - docker compose exec db mysql local_db -uroot -proot
