openapi: 3.0.3
info:
  title: API仕様書 - monorepo-openapi
  version: 0.1.0
  description: |
    ## 概要

    OpenAPIでbackendとfrontendをいい感じに管理するお試し実装のリポジトリ\
    `spec`で管理するOpenAPIのスキーマをマスタとして管理する

    ## アクセス制御

    | 環境        | ロール   |
    | ---------- | --------|
    | production | ✓       |
    | beta       | ✓       |
    | alpha      | ✓       |

    ## 問い合わせ

    * TBD
servers:
  - url: https://example.com
    description: プロダクション環境
  - url: https://beta.example.com
    description: ベータ環境
  - url: https://alpha.example.com
    description: アルファ環境
  - url: http://localhost:4000
    description: ローカル環境
tags:
  - name: Todo
    description: Todoリソースの操作を行うAPI群
paths:
  /todos:
    get:
      $ref: ./operations/findTodos.yaml
    post:
      $ref: ./operations/createTodo.yaml
  /todos/{id}:
    put:
      $ref: ./operations/updateTodo.yaml
    get:
      $ref: ./operations/getTodo.yaml
    delete:
      $ref: ./operations/deleteTodo.yaml
  /todos/{id}/complete:
    put:
      $ref: ./operations/completeTodo.yaml
components:
  schemas:
    ProblemDetails:
      $ref: ./schemas/problemDetails.yaml
    Todo:
      $ref: ./schemas/todo.yaml
    TodoId:
      $ref: ./schemas/todoId.yaml
